# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Thirty' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Thirty
  pod 'IQKeyboardManagerSwift'
  pod 'Firebase/Core' 
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'JHSpinner'
  pod 'SwiftyJSON'
  pod 'TwilioVideo', '2.0.0-beta2'
  pod 'Alamofire', '~> 4.7'

end
