# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Thirty' do
  use_frameworks!
  inhibit_all_warnings!

  # Pods for Thirty
  pod 'IQKeyboardManagerSwift'
  pod 'Firebase/Core', '~> 4.0'
  pod 'Firebase/Auth', '~> 4.0'
  pod 'Firebase/Database', '~> 4.0'
  pod 'JHSpinner'
  pod 'TwilioVideo'
  pod 'Alamofire', '~> 4.7'
  pod 'SCLAlertView'
  pod 'Kingfisher', '~> 4.0'
  pod 'SwipeCellKit'

end
